//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculation
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneDayData
    {
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public short DayKind { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
